//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace SevenMouths.Models
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Share))]
    public partial class Comment: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int CommentId
        {
            get { return _commentId; }
            set
            {
                if (_commentId != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'CommentId' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    if (!IsDeserializing)
                    {
                        if (Share != null && Share.ShareId != value)
                        {
                            Share = null;
                        }
                    }
                    _commentId = value;
                    OnPropertyChanged("CommentId");
                }
            }
        }
        private int _commentId;
    
        [DataMember]
        public Nullable<int> ShareId
        {
            get { return _shareId; }
            set
            {
                if (_shareId != value)
                {
                    _shareId = value;
                    OnPropertyChanged("ShareId");
                }
            }
        }
        private Nullable<int> _shareId;
    
        [DataMember]
        public Nullable<int> ParentId
        {
            get { return _parentId; }
            set
            {
                if (_parentId != value)
                {
                    _parentId = value;
                    OnPropertyChanged("ParentId");
                }
            }
        }
        private Nullable<int> _parentId;
    
        [DataMember]
        public Nullable<double> Grade
        {
            get { return _grade; }
            set
            {
                if (_grade != value)
                {
                    _grade = value;
                    OnPropertyChanged("Grade");
                }
            }
        }
        private Nullable<double> _grade;
    
        [DataMember]
        public string Description
        {
            get { return _description; }
            set
            {
                if (_description != value)
                {
                    _description = value;
                    OnPropertyChanged("Description");
                }
            }
        }
        private string _description;
    
        [DataMember]
        public Nullable<int> CommentedBy
        {
            get { return _commentedBy; }
            set
            {
                if (_commentedBy != value)
                {
                    _commentedBy = value;
                    OnPropertyChanged("CommentedBy");
                }
            }
        }
        private Nullable<int> _commentedBy;
    
        [DataMember]
        public Nullable<System.DateTime> CommentedAt
        {
            get { return _commentedAt; }
            set
            {
                if (_commentedAt != value)
                {
                    _commentedAt = value;
                    OnPropertyChanged("CommentedAt");
                }
            }
        }
        private Nullable<System.DateTime> _commentedAt;
    
        [DataMember]
        public Nullable<bool> IsOriginal
        {
            get { return _isOriginal; }
            set
            {
                if (_isOriginal != value)
                {
                    _isOriginal = value;
                    OnPropertyChanged("IsOriginal");
                }
            }
        }
        private Nullable<bool> _isOriginal;

        #endregion
        #region Navigation Properties
    
        [DataMember]
        public Share Share
        {
            get { return _share; }
            set
            {
                if (!ReferenceEquals(_share, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added && value != null)
                    {
                        // This the dependent end of an identifying relationship, so the principal end cannot be changed if it is already set,
                        // otherwise it can only be set to an entity with a primary key that is the same value as the dependent's foreign key.
                        if (CommentId != value.ShareId)
                        {
                            throw new InvalidOperationException("The principal end of an identifying relationship can only be changed when the dependent end is in the Added state.");
                        }
                    }
                    var previousValue = _share;
                    _share = value;
                    FixupShare(previousValue);
                    OnNavigationPropertyChanged("Share");
                }
            }
        }
        private Share _share;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        // This entity type is the dependent end in at least one association that performs cascade deletes.
        // This event handler will process notifications that occur when the principal end is deleted.
        internal void HandleCascadeDelete(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                this.MarkAsDeleted();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            Share = null;
        }

        #endregion
        #region Association Fixup
    
        private void FixupShare(Share previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && ReferenceEquals(previousValue.Comment, this))
            {
                previousValue.Comment = null;
            }
    
            if (Share != null)
            {
                Share.Comment = this;
                CommentId = Share.ShareId;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Share")
                    && (ChangeTracker.OriginalValues["Share"] == Share))
                {
                    ChangeTracker.OriginalValues.Remove("Share");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Share", previousValue);
                }
                if (Share != null && !Share.ChangeTracker.ChangeTrackingEnabled)
                {
                    Share.StartTracking();
                }
            }
        }

        #endregion
    }
}
