//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data.Common;
using System.Data.EntityClient;
using System.Data.Metadata.Edm;
using System.Data.Objects.DataClasses;
using System.Data.Objects;
using System.Data;
using System.Diagnostics;
using System.Globalization;
using System.Linq;

namespace SevenMouths.Models
{
    public partial class SevenMouthsEntities : ObjectContext
    {
        public const string ConnectionString = "name=SevenMouthsEntities";
        public const string ContainerName = "SevenMouthsEntities";
    
        #region Constructors
    
        public SevenMouthsEntities()
            : base(ConnectionString, ContainerName)
        {
            Initialize();
        }
    
        public SevenMouthsEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            Initialize();
        }
    
        public SevenMouthsEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            Initialize();
        }
    
        private void Initialize()
        {
            // Creating proxies requires the use of the ProxyDataContractResolver and
            // may allow lazy loading which can expand the loaded graph during serialization.
            ContextOptions.ProxyCreationEnabled = false;
            ObjectMaterialized += new ObjectMaterializedEventHandler(HandleObjectMaterialized);
        }
    
        private void HandleObjectMaterialized(object sender, ObjectMaterializedEventArgs e)
        {
            var entity = e.Entity as IObjectWithChangeTracker;
            if (entity != null)
            {
                bool changeTrackingEnabled = entity.ChangeTracker.ChangeTrackingEnabled;
                try
                {
                    entity.MarkAsUnchanged();
                }
                finally
                {
                    entity.ChangeTracker.ChangeTrackingEnabled = changeTrackingEnabled;
                }
                this.StoreReferenceKeyValues(entity);
            }
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Category> Categories
        {
            get { return _categories  ?? (_categories = CreateObjectSet<Category>("Categories")); }
        }
        private ObjectSet<Category> _categories;
    
        public ObjectSet<Comment> Comments
        {
            get { return _comments  ?? (_comments = CreateObjectSet<Comment>("Comments")); }
        }
        private ObjectSet<Comment> _comments;
    
        public ObjectSet<Cosite> Cosites
        {
            get { return _cosites  ?? (_cosites = CreateObjectSet<Cosite>("Cosites")); }
        }
        private ObjectSet<Cosite> _cosites;
    
        public ObjectSet<CoSiteUser> CoSiteUsers
        {
            get { return _coSiteUsers  ?? (_coSiteUsers = CreateObjectSet<CoSiteUser>("CoSiteUsers")); }
        }
        private ObjectSet<CoSiteUser> _coSiteUsers;
    
        public ObjectSet<Picture> Pictures
        {
            get { return _pictures  ?? (_pictures = CreateObjectSet<Picture>("Pictures")); }
        }
        private ObjectSet<Picture> _pictures;
    
        public ObjectSet<Role> Roles
        {
            get { return _roles  ?? (_roles = CreateObjectSet<Role>("Roles")); }
        }
        private ObjectSet<Role> _roles;
    
        public ObjectSet<ShareCategory> ShareCategories
        {
            get { return _shareCategories  ?? (_shareCategories = CreateObjectSet<ShareCategory>("ShareCategories")); }
        }
        private ObjectSet<ShareCategory> _shareCategories;
    
        public ObjectSet<SharePicture> SharePictures
        {
            get { return _sharePictures  ?? (_sharePictures = CreateObjectSet<SharePicture>("SharePictures")); }
        }
        private ObjectSet<SharePicture> _sharePictures;
    
        public ObjectSet<Share> Shares
        {
            get { return _shares  ?? (_shares = CreateObjectSet<Share>("Shares")); }
        }
        private ObjectSet<Share> _shares;
    
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get { return _sysdiagrams  ?? (_sysdiagrams = CreateObjectSet<sysdiagram>("sysdiagrams")); }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;
    
        public ObjectSet<UserRole> UserRoles
        {
            get { return _userRoles  ?? (_userRoles = CreateObjectSet<UserRole>("UserRoles")); }
        }
        private ObjectSet<UserRole> _userRoles;
    
        public ObjectSet<User> Users
        {
            get { return _users  ?? (_users = CreateObjectSet<User>("Users")); }
        }
        private ObjectSet<User> _users;
    
        public ObjectSet<Vote> Votes
        {
            get { return _votes  ?? (_votes = CreateObjectSet<Vote>("Votes")); }
        }
        private ObjectSet<Vote> _votes;

        #endregion
    }
}
