//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace SevenMouths.Models
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Comment))]
    [KnownType(typeof(Vote))]
    public partial class Share: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int ShareId
        {
            get { return _shareId; }
            set
            {
                if (_shareId != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'ShareId' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _shareId = value;
                    OnPropertyChanged("ShareId");
                }
            }
        }
        private int _shareId;
    
        [DataMember]
        public Nullable<int> ShareNum
        {
            get { return _shareNum; }
            set
            {
                if (_shareNum != value)
                {
                    _shareNum = value;
                    OnPropertyChanged("ShareNum");
                }
            }
        }
        private Nullable<int> _shareNum;
    
        [DataMember]
        public string Title
        {
            get { return _title; }
            set
            {
                if (_title != value)
                {
                    _title = value;
                    OnPropertyChanged("Title");
                }
            }
        }
        private string _title;
    
        [DataMember]
        public string Description
        {
            get { return _description; }
            set
            {
                if (_description != value)
                {
                    _description = value;
                    OnPropertyChanged("Description");
                }
            }
        }
        private string _description;
    
        [DataMember]
        public Nullable<int> SharedBy
        {
            get { return _sharedBy; }
            set
            {
                if (_sharedBy != value)
                {
                    _sharedBy = value;
                    OnPropertyChanged("SharedBy");
                }
            }
        }
        private Nullable<int> _sharedBy;
    
        [DataMember]
        public Nullable<System.DateTime> SharedAt
        {
            get { return _sharedAt; }
            set
            {
                if (_sharedAt != value)
                {
                    _sharedAt = value;
                    OnPropertyChanged("SharedAt");
                }
            }
        }
        private Nullable<System.DateTime> _sharedAt;
    
        [DataMember]
        public string Url
        {
            get { return _url; }
            set
            {
                if (_url != value)
                {
                    _url = value;
                    OnPropertyChanged("Url");
                }
            }
        }
        private string _url;

        #endregion
        #region Navigation Properties
    
        [DataMember]
        public TrackableCollection<Comment> Comments
        {
            get
            {
                if (_comments == null)
                {
                    _comments = new TrackableCollection<Comment>();
                    _comments.CollectionChanged += FixupComments;
                }
                return _comments;
            }
            set
            {
                if (!ReferenceEquals(_comments, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_comments != null)
                    {
                        _comments.CollectionChanged -= FixupComments;
                    }
                    _comments = value;
                    if (_comments != null)
                    {
                        _comments.CollectionChanged += FixupComments;
                    }
                    OnNavigationPropertyChanged("Comments");
                }
            }
        }
        private TrackableCollection<Comment> _comments;
    
        [DataMember]
        public TrackableCollection<Vote> Votes
        {
            get
            {
                if (_votes == null)
                {
                    _votes = new TrackableCollection<Vote>();
                    _votes.CollectionChanged += FixupVotes;
                }
                return _votes;
            }
            set
            {
                if (!ReferenceEquals(_votes, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_votes != null)
                    {
                        _votes.CollectionChanged -= FixupVotes;
                    }
                    _votes = value;
                    if (_votes != null)
                    {
                        _votes.CollectionChanged += FixupVotes;
                    }
                    OnNavigationPropertyChanged("Votes");
                }
            }
        }
        private TrackableCollection<Vote> _votes;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            Comments.Clear();
            Votes.Clear();
        }

        #endregion
        #region Association Fixup
    
        private void FixupComments(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (Comment item in e.NewItems)
                {
                    item.Share = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("Comments", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Comment item in e.OldItems)
                {
                    if (ReferenceEquals(item.Share, this))
                    {
                        item.Share = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("Comments", item);
                    }
                }
            }
        }
    
        private void FixupVotes(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (Vote item in e.NewItems)
                {
                    item.Share = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("Votes", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Vote item in e.OldItems)
                {
                    if (ReferenceEquals(item.Share, this))
                    {
                        item.Share = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("Votes", item);
                    }
                }
            }
        }

        #endregion
    }
}
